name: blog_app
description: A Complete Blog App using Flutter and Firebase

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  google_sign_in: ^4.5.6
  hive: ^1.4.4+1
  http: ^0.12.2
  injectable: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  freezed: ^0.12.6
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.6
  mockito: ^4.1.3
  pedantic: ^1.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
